=== JosephTridente/Progetto-Pizzeria-Ananas/Progetto-Pizzeria/menu.dtd
<!ELEMENT menu (categoria+)>
<!ELEMENT categoria (prodotto+)>
<!ATTLIST categoria nome CDATA REQUIRED>

<!ELEMENT prodotto (nome, prezzo)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>

=== JosephTridente/Progetto-Pizzeria-Ananas/Progetto-Pizzeria/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <categoria nome="Antipasti">
        <prodotto><nome>Bruschetta</nome><prezzo>4.00</prezzo></prodotto>
    </categoria>
    <categoria nome="Pizze">
        <prodotto><nome>Margherita</nome><prezzo>6.00</prezzo></prodotto>
        <prodotto><nome>Ananas Special</nome><prezzo>9.00</prezzo></prodotto>
    </categoria>
    <categoria nome="Bevande">
        <prodotto><nome>Birra Artigianale</nome><prezzo>5.00</prezzo></prodotto>
        <prodotto><nome>Acqua</nome><prezzo>2.00</prezzo></prodotto>
    </categoria>
    <categoria nome="Dolci">
        <prodotto><nome>Tiramis√π</nome><prezzo>5.00</prezzo></prodotto>
    </categoria>
</menu>
